### the frame config

spring.application.name: cat_manager_web
server.port: ${port:8081}

spring.datasource: 
 # dev
 url: jdbc:mysql://localhost:3306/cat_manager_web?useUnicode=yes&characterEncoding=UTF8&useSSL=false
 username: root
 password: isadmin
 driver-class-name: com.mysql.jdbc.Driver



spring.jpa:
  database: MYSQL
  show-sql: true
  hibernate.ddl-auto: validate
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  open-in-view: true